
function morse_code = english_to_morse(english_text)
    % Define Morse code dictionary as a map in MATLAB
    morse_dict = containers.Map( ...
        {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', ...
         'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ...
         '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', '.', ',', ...
         '?', '''', '!', '/', '(', ')', '&', ':', ';', '=', '+', '-', '_', ...
         '"', '$', '@'}, ...
        {'.-', '-...', '-.-.', '-..', '.', '..-.', '--.', '....', '..', ...
         '.---', '-.-', '.-..', '--', '-.', '---', '.--.', '--.-', '.-.', ...
         '...', '-', '..-', '...-', '.--', '-..-', '-.--', '--..', '-----', ...
         '.----', '..---', '...--', '....-', '.....', '-....', '--...', ...
         '---..', '----.', '/', '.-.-.-', '--..--', '..--..', '.----.', ...
         '-.-.--', '-..-.', '-.--.', '-.--.-', '.-...', '---...', '-.-.-.', ...
         '-...-', '.-.-.', '-....-', '..--.-', '.-..-.', '...-..-', '.--.-.'});

    % Convert input text to uppercase for consistency
  
    english_text = upper(english_text);

    % Initialize output
    morse_code = '';

    % Loop over each character in the input text
    for i = 1:length(english_text)
        char = english_text(i);
        if isKey(morse_dict, char)
            morse_code = [morse_code, morse_dict(char), ' '];
        else
            morse_code = [morse_code, '? ']; % Unknown characters as '?'
        end
    end

    % Remove trailing space
    morse_code = strtrim(morse_code);
end
