function english_text = morse_to_english(morse_code)
    % Define Morse code dictionary as a map in MATLAB
    morse_dict = containers.Map( ...
        {'.-', '-...', '-.-.', '-..', '.', '..-.', '--.', '....', '..', ...
         '.---', '-.-', '.-..', '--', '-.', '---', '.--.', '--.-', '.-.', ...
         '...', '-', '..-', '...-', '.--', '-..-', '-.--', '--..', '-----', ...
         '.----', '..---', '...--', '....-', '.....', '-....', '--...', ...
         '---..', '----.', '/', '.-.-.-', '--..--', '..--..', '.----.', ...
         '-.-.--', '-..-.', '-.--.', '-.--.-', '.-...', '---...', '-.-.-.', ...
         '-...-', '.-.-.', '-....-', '..--.-', '.-..-.', '...-..-', '.--.-.'}, ...
        {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', ...
         'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ...
         '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', '.', ',', ...
         '?', '''', '!', '/', '(', ')', '&', ':', ';', '=', '+', '-', '_', ...
         '"', '$', '@'});

    % Split the Morse code input into individual codes
    morse_chars = strsplit(morse_code, ' ');

    % Initialize output
    english_text = '';

    % Loop over each Morse code character
    for i = 1:length(morse_chars)
        char = morse_chars{i};
        if isKey(morse_dict, char)
            english_text = [english_text, morse_dict(char)];
        else
            english_text = [english_text, '?']; % Unknown characters as '?'
        end
    end
end
